# Generated by Django 4.2.13 on 2026-07-23 05:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo_class', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hazard_type',
            },
        ),
        migrations.CreateModel(
            name='HazardZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Red', 'Extreme'), ('Orange', 'Moderate'), ('Green', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('description', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangays.barangay')),
                ('hazard_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardtype')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hazard_zone',
            },
        ),
        migrations.CreateModel(
            name='HazardAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hazard_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardtype')),
                ('hazard_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazards.hazardzone')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hazard_alert',
            },
        ),
    ]
