# Generated by Django 5.2.17 on 2026-09-03 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('timeline_phase', models.CharField(choices=[('Before', 'Before'), ('During', 'During'), ('After', 'After')], max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hazard_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazards.hazardtype')),
            ],
            options={
                'db_table': 'guidance_content',
                'ordering': ['hazard_type', 'timeline_phase'],
            },
        ),
    ]
